name: Extract Secret Telemetry

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Azure via OIDC
        uses: azure/login@v2
        with:
          client-id: '494071c6-3230-4a4a-bc31-9bb7a5389320' # Your app-automation-bot ID
          tenant-id: 'd9e0787e-ef91-4c4f-a9b0-4660d5bfa4d8' # Replace with your Tenant ID if different
          subscription-id: '685eef6e-9bf2-48a5-bdfc-76e938fcd7e0' # Replace with your Subscription ID

      - name: Extract Secret from Key Vault
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: 'key-vault-sgt'
          secrets: 'secret-sgt'

      - name: Verify Secret Ingestion Visibility
        run: |
          echo "Data-Plane Target Acquired."
          # Azure automatically masks the secret value in the runner logs for safety
          echo "Secret extracted successfully: ${{ steps.retrieve-secret.outputs.secret-sgt != '' }}"
